############# English navigation ##############
# main menu    
[[main]]
name = "About Us"
URL = "about/"
weight = 2
  
[[main]]
name = "Services"
URL = "service/"
weight = 3

[[main]]
name = "Contact"
URL = "contact/"
weight = 4

#Footer menu
[[footer]]
name = "About Us"
URL = "about/"

[[footer]]
name = "Contact us"
URL = "contact/"

[[footer]]
name = "Services"
URL = "service/"